apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-ui
spec:
  selector:
    matchLabels:
      run: master-ui
  replicas: 1
  template:
    metadata:
      labels:
        run: master-ui
    spec:
      containers:
      - name: master-ui
        image: 889945364708.dkr.ecr.ap-south-1.amazonaws.com/aggrplatendtoend/master-ui:1-0-2
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: master-ui
  labels:
    run: master-ui
spec:
  ports:
  - port: 4200
    protocol: TCP
    targetPort: 4200
  type: LoadBalancer
  selector:
    run: master-ui
